from .productView import *
from .categoryPostView import *
from .categoryView import *
from .couponView import *
from .customerView import *
from .feedbackView import *
from .homeView import *
from .orderView import *
from .postView import *